"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from deutschland.interpol.exceptions import ApiAttributeError
from deutschland.interpol.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    OpenApiModel,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


def lazy_import():
    from deutschland.interpol.model.red_notice_detail_embedded import (
        RedNoticeDetailEmbedded,
    )
    from deutschland.interpol.model.un_notice_detail_links import UNNoticeDetailLinks

    globals()["RedNoticeDetailEmbedded"] = RedNoticeDetailEmbedded
    globals()["UNNoticeDetailLinks"] = UNNoticeDetailLinks


class UNNoticeDetail(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {}

    validations = {}

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (
            bool,
            date,
            datetime,
            dict,
            float,
            int,
            list,
            str,
            none_type,
        )  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            "summary": (str,),  # noqa: E501
            "weight": (int,),  # noqa: E501
            "profession": (str,),  # noqa: E501
            "purposes": ([str],),  # noqa: E501
            "entity_id": (str,),  # noqa: E501
            "aliases": ([str],),  # noqa: E501
            "father_name": (str,),  # noqa: E501
            "un_reference": (str,),  # noqa: E501
            "identity_documents": ([str],),  # noqa: E501
            "nationalities": ([str],),  # noqa: E501
            "name_at_birth": (str,),  # noqa: E501
            "name": (str,),  # noqa: E501
            "name_in_original_script": (str,),  # noqa: E501
            "un_resolution": (int,),  # noqa: E501
            "father_forename": (str,),  # noqa: E501
            "mother_forename": (str,),  # noqa: E501
            "forename": (str,),  # noqa: E501
            "associates": ([str],),  # noqa: E501
            "date_of_birth": (str,),  # noqa: E501
            "un_reference_date": (str,),  # noqa: E501
            "forename_in_original_script": (str,),  # noqa: E501
            "languages_spoken_ids": ([str],),  # noqa: E501
            "country_of_birth_id": (str,),  # noqa: E501
            "sex_id": (str,),  # noqa: E501
            "mother_name": (str,),  # noqa: E501
            "adresses": ([str],),  # noqa: E501
            "place_of_birth": (str,),  # noqa: E501
            "main_activity": (str,),  # noqa: E501
            "from_chamber_of_commerce": (str,),  # noqa: E501
            "legal_form": (str,),  # noqa: E501
            "administrators": ([str],),  # noqa: E501
            "additional_information": (str,),  # noqa: E501
            "registration_number": (str,),  # noqa: E501
            "formerly_known_as": (str,),  # noqa: E501
            "embedded": (RedNoticeDetailEmbedded,),  # noqa: E501
            "links": (UNNoticeDetailLinks,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None

    attribute_map = {
        "summary": "summary",  # noqa: E501
        "weight": "weight",  # noqa: E501
        "profession": "profession",  # noqa: E501
        "purposes": "purposes",  # noqa: E501
        "entity_id": "entity_id",  # noqa: E501
        "aliases": "aliases",  # noqa: E501
        "father_name": "father_name",  # noqa: E501
        "un_reference": "un_reference",  # noqa: E501
        "identity_documents": "identity_documents",  # noqa: E501
        "nationalities": "nationalities",  # noqa: E501
        "name_at_birth": "name_at_birth",  # noqa: E501
        "name": "name",  # noqa: E501
        "name_in_original_script": "name_in_original_script",  # noqa: E501
        "un_resolution": "un_resolution",  # noqa: E501
        "father_forename": "father_forename",  # noqa: E501
        "mother_forename": "mother_forename",  # noqa: E501
        "forename": "forename",  # noqa: E501
        "associates": "associates",  # noqa: E501
        "date_of_birth": "date_of_birth",  # noqa: E501
        "un_reference_date": "un_reference_date",  # noqa: E501
        "forename_in_original_script": "forename_in_original_script",  # noqa: E501
        "languages_spoken_ids": "languages_spoken_ids",  # noqa: E501
        "country_of_birth_id": "country_of_birth_id",  # noqa: E501
        "sex_id": "sex_id",  # noqa: E501
        "mother_name": "mother_name",  # noqa: E501
        "adresses": "adresses",  # noqa: E501
        "place_of_birth": "place_of_birth",  # noqa: E501
        "main_activity": "main_activity",  # noqa: E501
        "from_chamber_of_commerce": "from_chamber_of_commerce",  # noqa: E501
        "legal_form": "legal_form",  # noqa: E501
        "administrators": "administrators",  # noqa: E501
        "additional_information": "additional_information",  # noqa: E501
        "registration_number": "registration_number",  # noqa: E501
        "formerly_known_as": "formerly_known_as",  # noqa: E501
        "embedded": "_embedded",  # noqa: E501
        "links": "_links",  # noqa: E501
    }

    read_only_vars = {}

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """UNNoticeDetail - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            summary (str): [optional]  # noqa: E501
            weight (int): [optional]  # noqa: E501
            profession (str): [optional]  # noqa: E501
            purposes ([str]): [optional]  # noqa: E501
            entity_id (str): [optional]  # noqa: E501
            aliases ([str]): [optional]  # noqa: E501
            father_name (str): [optional]  # noqa: E501
            un_reference (str): [optional]  # noqa: E501
            identity_documents ([str]): [optional]  # noqa: E501
            nationalities ([str]): [optional]  # noqa: E501
            name_at_birth (str): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            name_in_original_script (str): [optional]  # noqa: E501
            un_resolution (int): [optional]  # noqa: E501
            father_forename (str): [optional]  # noqa: E501
            mother_forename (str): [optional]  # noqa: E501
            forename (str): [optional]  # noqa: E501
            associates ([str]): [optional]  # noqa: E501
            date_of_birth (str): [optional]  # noqa: E501
            un_reference_date (str): [optional]  # noqa: E501
            forename_in_original_script (str): [optional]  # noqa: E501
            languages_spoken_ids ([str]): [optional]  # noqa: E501
            country_of_birth_id (str): [optional]  # noqa: E501
            sex_id (str): [optional]  # noqa: E501
            mother_name (str): [optional]  # noqa: E501
            adresses ([str]): [optional]  # noqa: E501
            place_of_birth (str): [optional]  # noqa: E501
            main_activity (str): [optional]  # noqa: E501
            from_chamber_of_commerce (str): [optional]  # noqa: E501
            legal_form (str): [optional]  # noqa: E501
            administrators ([str]): [optional]  # noqa: E501
            additional_information (str): [optional]  # noqa: E501
            registration_number (str): [optional]  # noqa: E501
            formerly_known_as (str): [optional]  # noqa: E501
            embedded (RedNoticeDetailEmbedded): [optional]  # noqa: E501
            links (UNNoticeDetailLinks): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", True)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set(
        [
            "_data_store",
            "_check_type",
            "_spec_property_naming",
            "_path_to_item",
            "_configuration",
            "_visited_composed_classes",
        ]
    )

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """UNNoticeDetail - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            summary (str): [optional]  # noqa: E501
            weight (int): [optional]  # noqa: E501
            profession (str): [optional]  # noqa: E501
            purposes ([str]): [optional]  # noqa: E501
            entity_id (str): [optional]  # noqa: E501
            aliases ([str]): [optional]  # noqa: E501
            father_name (str): [optional]  # noqa: E501
            un_reference (str): [optional]  # noqa: E501
            identity_documents ([str]): [optional]  # noqa: E501
            nationalities ([str]): [optional]  # noqa: E501
            name_at_birth (str): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            name_in_original_script (str): [optional]  # noqa: E501
            un_resolution (int): [optional]  # noqa: E501
            father_forename (str): [optional]  # noqa: E501
            mother_forename (str): [optional]  # noqa: E501
            forename (str): [optional]  # noqa: E501
            associates ([str]): [optional]  # noqa: E501
            date_of_birth (str): [optional]  # noqa: E501
            un_reference_date (str): [optional]  # noqa: E501
            forename_in_original_script (str): [optional]  # noqa: E501
            languages_spoken_ids ([str]): [optional]  # noqa: E501
            country_of_birth_id (str): [optional]  # noqa: E501
            sex_id (str): [optional]  # noqa: E501
            mother_name (str): [optional]  # noqa: E501
            adresses ([str]): [optional]  # noqa: E501
            place_of_birth (str): [optional]  # noqa: E501
            main_activity (str): [optional]  # noqa: E501
            from_chamber_of_commerce (str): [optional]  # noqa: E501
            legal_form (str): [optional]  # noqa: E501
            administrators ([str]): [optional]  # noqa: E501
            additional_information (str): [optional]  # noqa: E501
            registration_number (str): [optional]  # noqa: E501
            formerly_known_as (str): [optional]  # noqa: E501
            embedded (RedNoticeDetailEmbedded): [optional]  # noqa: E501
            links (UNNoticeDetailLinks): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", False)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(
                    f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                    f"class with read only attributes."
                )
