"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_arrest_warrants_inner import (
    RedNoticeDetailArrestWarrantsInner,
)

from deutschland import interpol


class TestRedNoticeDetailArrestWarrantsInner(unittest.TestCase):
    """RedNoticeDetailArrestWarrantsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailArrestWarrantsInner(self):
        """Test RedNoticeDetailArrestWarrantsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailArrestWarrantsInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
