"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_images_embedded_images_inner_links import (
    RedNoticeDetailImagesEmbeddedImagesInnerLinks,
)

from deutschland import interpol

globals()[
    "RedNoticeDetailImagesEmbeddedImagesInnerLinks"
] = RedNoticeDetailImagesEmbeddedImagesInnerLinks
from deutschland.interpol.model.red_notice_detail_images_embedded_images_inner import (
    RedNoticeDetailImagesEmbeddedImagesInner,
)


class TestRedNoticeDetailImagesEmbeddedImagesInner(unittest.TestCase):
    """RedNoticeDetailImagesEmbeddedImagesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailImagesEmbeddedImagesInner(self):
        """Test RedNoticeDetailImagesEmbeddedImagesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailImagesEmbeddedImagesInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
