"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notice_detail_images_embedded_images import (
    UNNoticeDetailImagesEmbeddedImages,
)

from deutschland import interpol

globals()["UNNoticeDetailImagesEmbeddedImages"] = UNNoticeDetailImagesEmbeddedImages
from deutschland.interpol.model.un_notice_detail_images_embedded import (
    UNNoticeDetailImagesEmbedded,
)


class TestUNNoticeDetailImagesEmbedded(unittest.TestCase):
    """UNNoticeDetailImagesEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticeDetailImagesEmbedded(self):
        """Test UNNoticeDetailImagesEmbedded"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticeDetailImagesEmbedded()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
