"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_images_embedded_links_self import (
    RedNoticeDetailImagesEmbeddedLinksSelf,
)

from deutschland import interpol

globals()[
    "RedNoticeDetailImagesEmbeddedLinksSelf"
] = RedNoticeDetailImagesEmbeddedLinksSelf
from deutschland.interpol.model.red_notice_detail_images_embedded_links import (
    RedNoticeDetailImagesEmbeddedLinks,
)


class TestRedNoticeDetailImagesEmbeddedLinks(unittest.TestCase):
    """RedNoticeDetailImagesEmbeddedLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailImagesEmbeddedLinks(self):
        """Test RedNoticeDetailImagesEmbeddedLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailImagesEmbeddedLinks()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
