"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notice_detail_links_images import (
    UNNoticeDetailLinksImages,
)

from deutschland import interpol


class TestUNNoticeDetailLinksImages(unittest.TestCase):
    """UNNoticeDetailLinksImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticeDetailLinksImages(self):
        """Test UNNoticeDetailLinksImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticeDetailLinksImages()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
