"""
    Interpol: Interpol Red Notices API

    Interpol Red Notices Website API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_embedded import (
    RedNoticeDetailEmbedded,
)

from deutschland import interpol


class TestRedNoticeDetailEmbedded(unittest.TestCase):
    """RedNoticeDetailEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailEmbedded(self):
        """Test RedNoticeDetailEmbedded"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailEmbedded()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
