"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notices_links_self import UNNoticesLinksSelf

from deutschland import interpol


class TestUNNoticesLinksSelf(unittest.TestCase):
    """UNNoticesLinksSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticesLinksSelf(self):
        """Test UNNoticesLinksSelf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticesLinksSelf()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
