"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.interpol.api.default_api import DefaultApi  # noqa: E501

from deutschland import interpol


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_notices_v1_red_get(self):
        """Test case for notices_v1_red_get

        Get Red Notices  # noqa: E501
        """
        pass

    def test_notices_v1_red_notice_id_get(self):
        """Test case for notices_v1_red_notice_id_get

        Get Red Notice Details  # noqa: E501
        """
        pass

    def test_notices_v1_red_notice_id_images_get(self):
        """Test case for notices_v1_red_notice_id_images_get

        Get Red Notice Images  # noqa: E501
        """
        pass

    def test_notices_v1_un_get(self):
        """Test case for notices_v1_un_get

        Get UN Notices  # noqa: E501
        """
        pass

    def test_notices_v1_un_notice_type_notice_id_get(self):
        """Test case for notices_v1_un_notice_type_notice_id_get

        Get UN Notice Details  # noqa: E501
        """
        pass

    def test_notices_v1_un_notice_type_notice_id_images_get(self):
        """Test case for notices_v1_un_notice_type_notice_id_images_get

        Get UN Notice Images  # noqa: E501
        """
        pass

    def test_notices_v1_yellow_get(self):
        """Test case for notices_v1_yellow_get

        Get Yellow Notices  # noqa: E501
        """
        pass

    def test_notices_v1_yellow_notice_id_get(self):
        """Test case for notices_v1_yellow_notice_id_get

        Get Yellow Notice Details  # noqa: E501
        """
        pass

    def test_notices_v1_yellow_notice_id_images_get(self):
        """Test case for notices_v1_yellow_notice_id_images_get

        Get Yellow Notice Images  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
