"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notice_detail_images_embedded_links_self import (
    UNNoticeDetailImagesEmbeddedLinksSelf,
)

from deutschland import interpol


class TestUNNoticeDetailImagesEmbeddedLinksSelf(unittest.TestCase):
    """UNNoticeDetailImagesEmbeddedLinksSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticeDetailImagesEmbeddedLinksSelf(self):
        """Test UNNoticeDetailImagesEmbeddedLinksSelf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticeDetailImagesEmbeddedLinksSelf()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
