"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notice_detail_images_embedded_images_inner_links_self import (
    UNNoticeDetailImagesEmbeddedImagesInnerLinksSelf,
)

from deutschland import interpol

globals()[
    "UNNoticeDetailImagesEmbeddedImagesInnerLinksSelf"
] = UNNoticeDetailImagesEmbeddedImagesInnerLinksSelf
from deutschland.interpol.model.un_notice_detail_images_embedded_images_inner_links import (
    UNNoticeDetailImagesEmbeddedImagesInnerLinks,
)


class TestUNNoticeDetailImagesEmbeddedImagesInnerLinks(unittest.TestCase):
    """UNNoticeDetailImagesEmbeddedImagesInnerLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticeDetailImagesEmbeddedImagesInnerLinks(self):
        """Test UNNoticeDetailImagesEmbeddedImagesInnerLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticeDetailImagesEmbeddedImagesInnerLinks()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
