"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.yellow_notice_detail_images_embedded_images_inner_links import (
    YellowNoticeDetailImagesEmbeddedImagesInnerLinks,
)

from deutschland import interpol

globals()[
    "YellowNoticeDetailImagesEmbeddedImagesInnerLinks"
] = YellowNoticeDetailImagesEmbeddedImagesInnerLinks
from deutschland.interpol.model.yellow_notice_detail_images_embedded_images_inner import (
    YellowNoticeDetailImagesEmbeddedImagesInner,
)


class TestYellowNoticeDetailImagesEmbeddedImagesInner(unittest.TestCase):
    """YellowNoticeDetailImagesEmbeddedImagesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYellowNoticeDetailImagesEmbeddedImagesInner(self):
        """Test YellowNoticeDetailImagesEmbeddedImagesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = YellowNoticeDetailImagesEmbeddedImagesInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
