"""
    Interpol: Interpol Red Notices API

    Interpol Red Notices Website API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notices_embedded import RedNoticesEmbedded

from deutschland import interpol


class TestRedNoticesEmbedded(unittest.TestCase):
    """RedNoticesEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticesEmbedded(self):
        """Test RedNoticesEmbedded"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticesEmbedded()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
