"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.yellow_notice_detail_images_embedded_links import (
    YellowNoticeDetailImagesEmbeddedLinks,
)

from deutschland import interpol

globals()[
    "YellowNoticeDetailImagesEmbeddedLinks"
] = YellowNoticeDetailImagesEmbeddedLinks
from deutschland.interpol.model.yellow_notice_detail_images_embedded_images import (
    YellowNoticeDetailImagesEmbeddedImages,
)


class TestYellowNoticeDetailImagesEmbeddedImages(unittest.TestCase):
    """YellowNoticeDetailImagesEmbeddedImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYellowNoticeDetailImagesEmbeddedImages(self):
        """Test YellowNoticeDetailImagesEmbeddedImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = YellowNoticeDetailImagesEmbeddedImages()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
