"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notices_embedded import RedNoticesEmbedded
from deutschland.interpol.model.red_notices_query import RedNoticesQuery
from deutschland.interpol.model.un_notices_links import UNNoticesLinks

from deutschland import interpol

globals()["RedNoticesEmbedded"] = RedNoticesEmbedded
globals()["RedNoticesQuery"] = RedNoticesQuery
globals()["UNNoticesLinks"] = UNNoticesLinks
from deutschland.interpol.model.un_notices import UNNotices


class TestUNNotices(unittest.TestCase):
    """UNNotices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNotices(self):
        """Test UNNotices"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNotices()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
