"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_images_embedded import (
    RedNoticeDetailImagesEmbedded,
)
from deutschland.interpol.model.red_notice_detail_images_links import (
    RedNoticeDetailImagesLinks,
)

from deutschland import interpol

globals()["RedNoticeDetailImagesEmbedded"] = RedNoticeDetailImagesEmbedded
globals()["RedNoticeDetailImagesLinks"] = RedNoticeDetailImagesLinks
from deutschland.interpol.model.red_notice_detail_images import RedNoticeDetailImages


class TestRedNoticeDetailImages(unittest.TestCase):
    """RedNoticeDetailImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailImages(self):
        """Test RedNoticeDetailImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailImages()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
