"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notices_links_last import UNNoticesLinksLast
from deutschland.interpol.model.un_notices_links_next import UNNoticesLinksNext
from deutschland.interpol.model.un_notices_links_self import UNNoticesLinksSelf

from deutschland import interpol

globals()["UNNoticesLinksLast"] = UNNoticesLinksLast
globals()["UNNoticesLinksNext"] = UNNoticesLinksNext
globals()["UNNoticesLinksSelf"] = UNNoticesLinksSelf
from deutschland.interpol.model.un_notices_links import UNNoticesLinks


class TestUNNoticesLinks(unittest.TestCase):
    """UNNoticesLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticesLinks(self):
        """Test UNNoticesLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticesLinks()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
