"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.yellow_notice_detail_images_embedded_images_inner_links_self import (
    YellowNoticeDetailImagesEmbeddedImagesInnerLinksSelf,
)
from deutschland.interpol.model.yellow_notice_detail_images_links_notice import (
    YellowNoticeDetailImagesLinksNotice,
)
from deutschland.interpol.model.yellow_notice_detail_images_links_self import (
    YellowNoticeDetailImagesLinksSelf,
)

from deutschland import interpol

globals()[
    "YellowNoticeDetailImagesEmbeddedImagesInnerLinksSelf"
] = YellowNoticeDetailImagesEmbeddedImagesInnerLinksSelf
globals()["YellowNoticeDetailImagesLinksNotice"] = YellowNoticeDetailImagesLinksNotice
globals()["YellowNoticeDetailImagesLinksSelf"] = YellowNoticeDetailImagesLinksSelf
from deutschland.interpol.model.yellow_notice_detail_images_links import (
    YellowNoticeDetailImagesLinks,
)


class TestYellowNoticeDetailImagesLinks(unittest.TestCase):
    """YellowNoticeDetailImagesLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYellowNoticeDetailImagesLinks(self):
        """Test YellowNoticeDetailImagesLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = YellowNoticeDetailImagesLinks()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
