"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_arrest_warrants_inner import (
    RedNoticeDetailArrestWarrantsInner,
)
from deutschland.interpol.model.red_notice_detail_embedded import (
    RedNoticeDetailEmbedded,
)
from deutschland.interpol.model.red_notice_detail_links import RedNoticeDetailLinks

from deutschland import interpol

globals()["RedNoticeDetailArrestWarrantsInner"] = RedNoticeDetailArrestWarrantsInner
globals()["RedNoticeDetailEmbedded"] = RedNoticeDetailEmbedded
globals()["RedNoticeDetailLinks"] = RedNoticeDetailLinks
from deutschland.interpol.model.red_notice_detail import RedNoticeDetail


class TestRedNoticeDetail(unittest.TestCase):
    """RedNoticeDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetail(self):
        """Test RedNoticeDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetail()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
