"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_embedded import (
    RedNoticeDetailEmbedded,
)
from deutschland.interpol.model.yellow_notice_detail_links import (
    YellowNoticeDetailLinks,
)

from deutschland import interpol

globals()["RedNoticeDetailEmbedded"] = RedNoticeDetailEmbedded
globals()["YellowNoticeDetailLinks"] = YellowNoticeDetailLinks
from deutschland.interpol.model.yellow_notice_detail import YellowNoticeDetail


class TestYellowNoticeDetail(unittest.TestCase):
    """YellowNoticeDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYellowNoticeDetail(self):
        """Test YellowNoticeDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = YellowNoticeDetail()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
