"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notice_detail_images_links_self import (
    UNNoticeDetailImagesLinksSelf,
)

from deutschland import interpol


class TestUNNoticeDetailImagesLinksSelf(unittest.TestCase):
    """UNNoticeDetailImagesLinksSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticeDetailImagesLinksSelf(self):
        """Test UNNoticeDetailImagesLinksSelf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticeDetailImagesLinksSelf()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
