"""
    Interpol: Interpol Red Notices API

    Interpol Red Notices Website API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notices_links_self import RedNoticesLinksSelf

from deutschland import interpol

globals()["RedNoticesLinksSelf"] = RedNoticesLinksSelf
from deutschland.interpol.model.red_notices_links import RedNoticesLinks


class TestRedNoticesLinks(unittest.TestCase):
    """RedNoticesLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticesLinks(self):
        """Test RedNoticesLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticesLinks()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
