"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_images_embedded_images_inner import (
    RedNoticeDetailImagesEmbeddedImagesInner,
)

from deutschland import interpol

globals()[
    "RedNoticeDetailImagesEmbeddedImagesInner"
] = RedNoticeDetailImagesEmbeddedImagesInner
from deutschland.interpol.model.red_notice_detail_images_embedded import (
    RedNoticeDetailImagesEmbedded,
)


class TestRedNoticeDetailImagesEmbedded(unittest.TestCase):
    """RedNoticeDetailImagesEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailImagesEmbedded(self):
        """Test RedNoticeDetailImagesEmbedded"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailImagesEmbedded()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
