"""
    Interpol: Interpol Red Notices API

    Interpol Red Notices Website API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_images_links_thumbnail import (
    RedNoticeDetailImagesLinksThumbnail,
)

from deutschland import interpol


class TestRedNoticeDetailImagesLinksThumbnail(unittest.TestCase):
    """RedNoticeDetailImagesLinksThumbnail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailImagesLinksThumbnail(self):
        """Test RedNoticeDetailImagesLinksThumbnail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailImagesLinksThumbnail()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
