"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.yellow_notice_detail_images_embedded import (
    YellowNoticeDetailImagesEmbedded,
)
from deutschland.interpol.model.yellow_notice_detail_images_links import (
    YellowNoticeDetailImagesLinks,
)

from deutschland import interpol

globals()["YellowNoticeDetailImagesEmbedded"] = YellowNoticeDetailImagesEmbedded
globals()["YellowNoticeDetailImagesLinks"] = YellowNoticeDetailImagesLinks
from deutschland.interpol.model.yellow_notice_detail_images import (
    YellowNoticeDetailImages,
)


class TestYellowNoticeDetailImages(unittest.TestCase):
    """YellowNoticeDetailImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYellowNoticeDetailImages(self):
        """Test YellowNoticeDetailImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = YellowNoticeDetailImages()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
