"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.yellow_notice_detail_links_images import (
    YellowNoticeDetailLinksImages,
)

from deutschland import interpol


class TestYellowNoticeDetailLinksImages(unittest.TestCase):
    """YellowNoticeDetailLinksImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYellowNoticeDetailLinksImages(self):
        """Test YellowNoticeDetailLinksImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = YellowNoticeDetailLinksImages()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
