"""
    Interpol: Interpol Red Notices API

    Interpol Red Notices Website API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_images_links_self import (
    RedNoticeDetailImagesLinksSelf,
)

from deutschland import interpol


class TestRedNoticeDetailImagesLinksSelf(unittest.TestCase):
    """RedNoticeDetailImagesLinksSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailImagesLinksSelf(self):
        """Test RedNoticeDetailImagesLinksSelf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailImagesLinksSelf()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
