"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notice_detail_images_embedded import (
    UNNoticeDetailImagesEmbedded,
)
from deutschland.interpol.model.un_notice_detail_images_links import (
    UNNoticeDetailImagesLinks,
)

from deutschland import interpol

globals()["UNNoticeDetailImagesEmbedded"] = UNNoticeDetailImagesEmbedded
globals()["UNNoticeDetailImagesLinks"] = UNNoticeDetailImagesLinks
from deutschland.interpol.model.un_notice_detail_images import UNNoticeDetailImages


class TestUNNoticeDetailImages(unittest.TestCase):
    """UNNoticeDetailImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticeDetailImages(self):
        """Test UNNoticeDetailImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticeDetailImages()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
