"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.yellow_notice_detail_images_links_notice import (
    YellowNoticeDetailImagesLinksNotice,
)

from deutschland import interpol


class TestYellowNoticeDetailImagesLinksNotice(unittest.TestCase):
    """YellowNoticeDetailImagesLinksNotice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYellowNoticeDetailImagesLinksNotice(self):
        """Test YellowNoticeDetailImagesLinksNotice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = YellowNoticeDetailImagesLinksNotice()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
