"""
    Interpol: Interpol Red Notices API

    Interpol Red Notices Website API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.red_notice_detail_images_embedded_links_self import (
    RedNoticeDetailImagesEmbeddedLinksSelf,
)

from deutschland import interpol


class TestRedNoticeDetailImagesEmbeddedLinksSelf(unittest.TestCase):
    """RedNoticeDetailImagesEmbeddedLinksSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedNoticeDetailImagesEmbeddedLinksSelf(self):
        """Test RedNoticeDetailImagesEmbeddedLinksSelf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RedNoticeDetailImagesEmbeddedLinksSelf()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
