"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notice_detail_images_links_notice import (
    UNNoticeDetailImagesLinksNotice,
)
from deutschland.interpol.model.un_notice_detail_images_links_self import (
    UNNoticeDetailImagesLinksSelf,
)
from deutschland.interpol.model.un_notice_detail_images_links_thumbnail import (
    UNNoticeDetailImagesLinksThumbnail,
)

from deutschland import interpol

globals()["UNNoticeDetailImagesLinksNotice"] = UNNoticeDetailImagesLinksNotice
globals()["UNNoticeDetailImagesLinksSelf"] = UNNoticeDetailImagesLinksSelf
globals()["UNNoticeDetailImagesLinksThumbnail"] = UNNoticeDetailImagesLinksThumbnail
from deutschland.interpol.model.un_notice_detail_images_links import (
    UNNoticeDetailImagesLinks,
)


class TestUNNoticeDetailImagesLinks(unittest.TestCase):
    """UNNoticeDetailImagesLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticeDetailImagesLinks(self):
        """Test UNNoticeDetailImagesLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticeDetailImagesLinks()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
