"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notices_links_last import UNNoticesLinksLast

from deutschland import interpol


class TestUNNoticesLinksLast(unittest.TestCase):
    """UNNoticesLinksLast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticesLinksLast(self):
        """Test UNNoticesLinksLast"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticesLinksLast()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
