"""
    Interpol Notices API

    Interpol Red, Yellow and UN Notices API  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.interpol.model.un_notice_detail_images_embedded_links_self import (
    UNNoticeDetailImagesEmbeddedLinksSelf,
)

from deutschland import interpol

globals()[
    "UNNoticeDetailImagesEmbeddedLinksSelf"
] = UNNoticeDetailImagesEmbeddedLinksSelf
from deutschland.interpol.model.un_notice_detail_images_embedded_links import (
    UNNoticeDetailImagesEmbeddedLinks,
)


class TestUNNoticeDetailImagesEmbeddedLinks(unittest.TestCase):
    """UNNoticeDetailImagesEmbeddedLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUNNoticeDetailImagesEmbeddedLinks(self):
        """Test UNNoticeDetailImagesEmbeddedLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UNNoticeDetailImagesEmbeddedLinks()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
